device = require 'low.Core.Modules.device'
graphics = require 'low.Core.Modules.graphics'
scene = require 'low.Core.Modules.scene'
event = require 'low.Core.Modules.event'
loop = require 'low.Core.Modules.loop'
notification = require 'low.Core.Modules.notification'
save = require 'low.Core.Modules.save'
